# Generated by Django 5.0.3 on 2024-03-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_column='tag_name', max_length=200),
        ),
    ]
