# Generated by Django 5.0.3 on 2024-03-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_tag_create_time_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_time', 'name']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
